name:                b-line
version:             0.1.0.0
github:              emersoncoskey/b-line
license:             BSD3
author:              Emerson Coskey
maintainer:          56370779+emersoncoskey@users.noreply.github.com
copyright:           2022 Emerson Coskey

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/emersoncoskey/b-line#readme>

dependencies:
- base >= 4.16 && < 10
- rio >= 0.1.22
- path >= 0.9
- microlens-th >= 0.4.3
- aeson >= 2.0
- optparse-applicative >= 0.17
- brick >= 1.4
- req >= 3.13
- http-api-data >= 0.4.3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  b-line-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - b-line
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  b-line-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - b-line
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
